### ISSUE TITLE
Python(Go) - poetry - dependencies listed in METADAT file are not displayed in SPDX file

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#146]
@lfpratik 
**Tool Version** Cloned code from main branch of https://github.com/spdx/spdx-sbom-generator on 11-06-2021 and built the tool
**Test Repo** https://github.com/lfpratik/spdx-poetry-demo
**OS** Windows 10

1. Followed all prerequisite steps as per https://confluence.linuxfoundation.org/display/PROD/SPDX+-+Python+Module+-+Prerequisites+For+Windows
2. Followed Prerequisite and Steps as per below screenshot
![image](https://user-images.githubusercontent.com/73597479/121684233-0cb90500-cadc-11eb-88cb-d0be8a627ccf.png)
3. Execute ./spdx-sbom-generator
4. Observed that all dependencies listed in METADAT file are not displayed in SPDX file
**Example1**
![image](https://user-images.githubusercontent.com/73597479/121686774-3cb5d780-cadf-11eb-8d9c-082c5bff082c.png)

![image](https://user-images.githubusercontent.com/73597479/121686736-3293d900-cadf-11eb-8851-954b7a2212d6.png)

**Example2**
![image](https://user-images.githubusercontent.com/73597479/121687192-b0f07b00-cadf-11eb-8b37-57a8de6ea71d.png)

![image](https://user-images.githubusercontent.com/73597479/121687157-a2a25f00-cadf-11eb-91b6-8aa21773cdb6.png)

**Comment by lfpratik** [comment]
Just for the log tester python version is 3.9.5

**Comment by lfpratik** [comment]
@niruautomation, my first thought on the highlighted packages those packages are not installed due to the dependency on the python version required for them. 
`pyrsistent` required python < 3 version
`enum34` required python < 3.4 version

If your current python version higher side then it will not least into SPDX files it will get skip into the dependency tree.

I believe it is the expected output.  @licquia can you confirm this I am imaging this case will occur on the pure python side.

cc: @licquia and @niravpatel27

**Comment by niruautomation** [comment]
@lfpratik @licquia @niravpatel27 
Could you please confirm what is the expected behavior

**Comment by licquia** [comment]
Our expected behavior is that these modules are not present unless you are running an older version of Python (3.4 or earlier in the case of `enum34`, or Python 2.x with `pyrsistent`.  So I believe it's correct that these modules are not present in the SPDX file.

**Comment by niruautomation** [comment]
Verified packages as per above comment and observed that dependencies are fetched as expected
