### ISSUE TITLE
SSB-49: PHP - Instead of dist.url value NOASSERTION is displayed for PackageDownloadLocation even when there is dist.url in composer.lock 

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#97]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-49

spdx-sbom-generator tool version v0.0.2Test Repo that I used for testinghttps://github.com/woocommerce/woocommerceObserved that instead of dist.url value NOASSERTION is displayed for PackageDownloadLocation even when there is dist.url in composer.lock . As described in Spec, dist.url should be displayed for the field. Observed this issue for all packagesSPDX data (PFA SPDX for reference)Composer.lock

**Comment by niruautomation** [comment]
@luismoriguerra 
Verified with v0.0.8 and observed that ${package.source.url} is displayed instead of ${package.dist.url} for PackageDownloadLocation

**SPDX files**
[bom-composer_laravel_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721117/bom-composer_laravel_v0.0.8_27-Jun-2021.spdx.txt)
[bom-composer_utf8_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721118/bom-composer_utf8_v0.0.8_27-Jun-2021.spdx.txt)
[bom-composer_woocommerce_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721119/bom-composer_woocommerce_v0.0.8_27-Jun-2021.spdx.txt)

**Specification**
![image](https://user-images.githubusercontent.com/73597479/123534876-ecc14c80-d73d-11eb-94fc-2998ae41b951.png)

**Comment by niruautomation** [comment]
Cloned latest code and build the tool and verified that the issue is fixed
[bom-composer_laravel_01-July-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6753251/bom-composer_laravel_01-July-2021.spdx.txt)
[bom-composer_utf8_01-July-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6753252/bom-composer_utf8_01-July-2021.spdx.txt)
[bom-composer_woocommerce_01-July-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6753255/bom-composer_woocommerce_01-July-2021.spdx.txt)
