### ISSUE TITLE
SSB-48: PHP - Instead of author details NOASSERTION is displayed for PackageSupplier even when there is author details on composer.lock 

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#98]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-48

spdx-sbom-generator tool version v0.0.2Test Repo that I used for testinghttps://github.com/woocommerce/woocommerceObserved that instead of author details NOASSERTION is displayed for PackageSupplier even when there is author details on composer.lock. As described in Spec, author details should be displayed for the field. Observed this issue for all packagesSPDX data (PFA SPDX for reference)Composer.lock

**Comment by niruautomation** [comment]
Verified that PackageSupplier is displayed as per specification. However in current release only first author name is displayed instead of all authors

**Specification**
![image](https://user-images.githubusercontent.com/73597479/123534994-b20be400-d73e-11eb-9713-71c01352533f.png)

**SPDX files**
[bom-composer_woocommerce_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721128/bom-composer_woocommerce_v0.0.8_27-Jun-2021.spdx.txt)
[bom-composer_utf8_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721129/bom-composer_utf8_v0.0.8_27-Jun-2021.spdx.txt)
[bom-composer_laravel_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721130/bom-composer_laravel_v0.0.8_27-Jun-2021.spdx.txt)
